"use client"

import { createContext, useContext, useState } from "react"

export type Lang = "sr" | "en"

export const t = {
  sr: {
    nav: {
      products: "Proizvodi",
      createAr: "Kreiraj AR stranicu",
      publishedLinks: "Objavljeni linkovi",
      analytics: "Analitika",
      billing: "Naplata",
      logout: "Odjavi se",
      footer: "Modeli su pregledani od strane čoveka pre objavljivanja. Pilot: 10–25 proizvoda.",
      brand: "Pilot komandni centar",
      demoBadge: "Pilot radni prostor",
    },
    langToggle: "EN",

    dashboard: {
      eyebrow: "Pilot komandni centar",
      heading: "Vaša AR kontrolna tabla",
      subtitle: "Počnite dodavanjem prvog proizvoda. Pravi proizvodi, linkovi i AR metrike će se pojaviti ovde kada budu kreirani.",
      createBtn: "+ Kreiraj AR stranicu",
      catalogStatus: "Status kataloga",
      noProducts: "Još nema proizvoda",
      publishedPages: "Objavljene stranice",
      hostedLive: "Još ništa nije objavljeno",
      arClicks: "AR klikovi",
      noActivity: "Nema aktivnosti",
      storeClicks: "Klikovi na prodavnicu",
      backToStore: "Nema klikova",
      nextActions: "Sledeće potrebne radnje",
      emptyActionDesc: "Kreirajte prvi AR proizvod da biste testirali upload, 3D pregled i objavljivanje hostovanog linka.",
      addProduct: "Dodaj proizvod",
      actionItemTitle: "Kreirajte prvi AR proizvod",
      actionItemDesc: "Unesite detalje proizvoda, dimenzije i fotografije, zatim pregledajte 3D model kada bude spreman.",
      planUsage: "Korišćenje trenutnog plana",
      pagesPublished: "pilot hostovanih stranica objavljeno.",
      billingNote: "Kreiranje modela se naplaćuje po odobrenom modelu. Pretplata za hostovanu stranicu pokriva sve aktivne stranice.",
      humanReviewed: "Pregledano od strane čoveka pre objavljivanja",
      viewBilling: "Pogledaj detalje naplate →",
      productsHeading: "Proizvodi",
      productsDesc: "Još nema stvarnih proizvoda. Ova tabela će prikazati statuse, linkove i metrike kada dodate prvi proizvod.",
      publishedLinksBtn: "Objavljeni linkovi",
      emptyProductsTitle: "Još nema proizvoda",
      emptyProductsDesc: "Kreirajte prvi AR proizvod da biste počeli testiranje dashboarda.",
    },

    table: {
      product: "Proizvod",
      status: "Status",
      nextAction: "Sledeća akcija",
      hostedLink: "Hostovani link",
      arClicks: "AR klikovi",
      storeClicks: "Klikovi na prodavnicu",
      photos: "fotografija",
      copyLink: "Kopiraj hostovani link",
      notLive: "Još nije aktivno",
      addPhotos: "Dodaj fotografije",
      waitingModel: "Čekanje na model",
      reviewPreview: "Pregledaj pregled",
      publishLink: "Objavi link",
      viewAnalytics: "Pogledaj analitiku",
      reviewDetails: "Pregledaj detalje",
      emptyTitle: "Još nema proizvoda",
      emptyDescription: "Kreirajte prvi AR proizvod da biste ovde videli statuse, linkove i metrike.",
    },

    analytics: {
      eyebrow: "Analitika",
      heading: "Angažovanost kupaca",
      subtitle: "Pregledi stranica, interakcije sa 3D pregledačem, AR klikovi i CTA klikovi na prodavnicu — po proizvodu.",
      viewBilling: "Pogledaj naplatu",
      pageViews: "Pregledi stranica",
      allProducts: "Svi proizvodi",
      embedViews: "Pregledi ugradnje",
      embedded: "Ugrađeno na prodavnicama",
      viewerInteractions: "Interakcije sa pregledačem",
      engagements3d: "3D angažovanost",
      arClicks: "AR klikovi",
      viewInRoom: "Pogledaj u prostoriji",
      storeCta: "CTA klikovi na prodavnicu",
      backToStore: "Nazad u prodavnicu",
      breakdown: "Pregled po proizvodu",
      breakdownDesc: "Metrike angažovanosti za svaku objavljenu stranicu proizvoda.",
      colProduct: "Proizvod",
      colPageViews: "Pregledi",
      colEmbedViews: "Pregledi ugradnje",
      colInteractions: "Interakcije",
      colArClicks: "AR klikovi",
      colStoreClicks: "Klikovi na prodavnicu",
      colTopDevices: "Vodeći uređaji",
      noData: "Nema podataka",
    },

    billing: {
      eyebrow: "Naplata",
      heading: "Pilot plan i troškovi",
      subtitle: "Naknada po odobrenom modelu plus mesečna pretplata za hostovanu stranicu. Jednostavno i predvidivo.",
      viewAnalytics: "Pogledaj analitiku",
      planUsageHeading: "Korišćenje trenutnog plana",
      planUsageSub: "10–25 SKU pilot",
      active: "Aktivan",
      pagesPublished: "pilot hostovanih stranica objavljeno",
      pageLive: "stranica aktivno",
      pagesLive: "stranica aktivno",
      pageRemaining: "stranica preostalo",
      pagesRemaining: "stranica preostalo",
      humanReviewed: "Pregledano od strane čoveka pre objavljivanja",
      subscriptionHeading: "Plan pretplate",
      subscriptionDesc: "Nadogradite u bilo kom trenutku. Promene stupaju na snagu odmah.",
      currentPlan: "Trenutni plan",
      popular: "Popularno",
      custom: "Po dogovoru",
      perMonth: "/mes",
      skus: "SKU-ovi",
      storage: "Skladište",
      views: "Pregledi",
      upgradeTo: "Nadogradite na",
      downgradeTo: "Smanjite na",
      talkToUs: "Kontaktirajte nas",
      pricingHeading: "Pregled cena",
      pricingDesc: "Naplaćuje se po odobrenom modelu plus mesečna pretplata za hostovane stranice. Revizija ili regeneracija se naplaćuje samo kada se zatraži nova verzija nakon što odobreni model već postoji.",
      includedHeading: "Šta je uključeno u pilot",
      includedItems: [
        ["Vođeni upload fotografija", "Korak-po-korak lista za sve potrebne uglove proizvoda."],
        ["Generisanje modela", "Automatsko pokretanje generisanja za svaki poslati proizvod."],
        ["Pregled kvaliteta od strane čoveka", "Ručna kapija odobrenja pre nego što stranica postane aktivna."],
        ["Hostovana stranica proizvoda", "Javni link za vašu prodavnicu, email, oglas ili QR kod."],
        ["3D pregledač i AR pokretanje", "Kupci pregledaju proizvod u 3D i pokreću AR na podržanim uređajima."],
        ["Analitika angažovanosti", "Pregledi stranica, AR klikovi i CTA klikovi na prodavnicu — po proizvodu."],
      ] as [string, string][],
    },

    create: {
      eyebrow: "Kreiraj AR stranicu",
      heading: "Vođeno podešavanje proizvoda",
      subtitle: "Dodajte proizvod, otpremite potrebne fotografije, zatim pokrenite automatsko generisanje 3D modela.",
      backBtn: "Nazad na proizvode",
      steps: ["Detalji proizvoda", "Dimenzije", "URL prodavnice", "Vođeni upload fotografija", "Generiši 3D model"],
      detailsHeading: "Detalji proizvoda",
      productName: "Naziv proizvoda",
      category: "Kategorija proizvoda",
      description: "Kratki opis proizvoda",
      dimensionsHeading: "Dimenzije",
      width: "Širina cm",
      height: "Visina cm",
      depth: "Dubina cm",
      storeUrlHeading: "URL prodavnice",
      storeUrl: "Stranica proizvoda na vašoj prodavnici",
      price: "Prikaz cene (opciono)",
      submitBtn: "Generiši 3D model",
      photoEyebrow: "Vođeni upload fotografija",
      photoHeading: "Fotografije potrebne pre generisanja",
      photoDesc: "Koristite jasne, dobro osvetljene fotografije na jednostavnoj pozadini. Nakon generisanja ćete videti 3D pregled pre objavljivanja.",
      photoChecklist: [
        ["Prednja strana", "Fotografija proizvoda direktno sa prednje strane"],
        ["Zadnja strana", "Pogled sa zadnje strane sa vidljivim punim obrisom"],
        ["Leva strana", "Bočni profil za dubinu i noge ili naslone"],
        ["Desna strana", "Profil suprotne strane"],
        ["Gornji ili kosi ugao", "Prikazuje dubinu, sedište, površinu ili oblik senke"],
        ["Fotografije materijala/detalja", "Krupni planovi tkanine, drvenih vlakana, metalne opreme ili teksture"],
        ["Fotografija za merilo/kontekst", "Opcionalna fotografija u prostoriji ili rukom kada je korisno"],
      ] as [string, string][],
      ready: "Spremno",
      needed: "Potrebno",
      uploadBtn: "Otpremi",
      changeBtn: "Zameni",
      submittingBtn: "Pokretanje generisanja...",
      assumptionNote: (name: string) =>
        `${name} ima dovoljno osnovnih uglova za početak, ali fotografije materijala/detalja i merila poboljšavaju ocenu poverenja recenzenta.`,
    },

    publishedLinks: {
      eyebrow: "Objavljeni linkovi",
      heading: "Aktivne hostovane stranice proizvoda",
      subtitle: "Kopirajte linkove za vašu prodavnicu, oglase, emailove ili QR kodove.",
      createBtn: "Kreiraj AR stranicu",
      verifiedLive: "Verifikovano i aktivno",
      notPublished: "Nije objavljeno",
      hostedLink: "Hostovani link",
      preview: "Pregled",
      availableAfter: "Dostupno nakon odobrenja i objavljivanja.",
      ctaDestination: "CTA odredište:",
      embedHeading: "Ugradi na svoju prodavnicu",
      embedHint: "Nalepite ovaj kod na stranicu proizvoda (Shopify, WooCommerce, Wix ili sopstveni sajt).",
      copyEmbed: "Kopiraj kod za ugradnju",
    },

    approval: {
      eyebrow: "Status odobrenja",
      heading: "Ručni pregled kontroliše objavljivanje",
      subtitle: "Nijedna javna hostovana stranica ne postaje aktivna dok model proizvoda ne bude odobren.",
      checks: [
        "Model liči na proizvod.",
        "Orijentacija i razmera su ispravni.",
        "Teksture i geometrija su prihvatljivi.",
        "Javni pregled se učitava pre objavljivanja.",
      ],
      reviewerNote: "Napomena recenzenta:",
      merchantStatus: "Status prodavca",
      merchantDesc: "Prodavci vide jednostavan status pregleda. Interna razloga za odbijanje mogu biti prevedena u jasne korake za regeneraciju.",
      awaitingReview: "Na čekanju pregleda",
      hostedSettings: "Podešavanja hostovane stranice",
    },

    status: {
      eyebrow: "Status generisanja",
      subtitle: "Fotografije su poslate u obradu. Model će se pojaviti čim se završe generisanje i pakovanje AR fajlova.",
      photoSetFallback: "aktivnom setu fotografija",
      fallbackHeading: "Šta se dešava sledeće",
      fallbackDesc: "Aplikacija prvo generiše 3D model, zatim pakuje web i AR fajlove. Ako rezultat nije dobar, može se pokrenuti regenerisanje bez menjanja javne stranice.",
      generationRunning: "3D generisanje u toku",
      providerJob: "Interni posao",
      tripoAvailable: "Rezervno generisanje dostupno",
      fallbackLocked: "Rezervna opcija zaključana",
      viewLastModel: "Otvori generisani model",
      stageDetails: [
        (photoCount: number, photoSetId: string) =>
          `${photoCount} fotografija uskladišteno u ${photoSetId}.`,
        (passed: number, total: number) =>
          `${passed}/${total} provera prošlo pre slanja provajderu.`,
        (_provider: string, status: string) =>
          `Status obrade: ${status}.`,
        "Sirovi izlaz provajdera se skladišti pre pakovanja GLB, USDZ, postera, sličice i metapodataka.",
        "Aplikacija proverava učitavanje modela, veličinu, dimenzije, teksture, prikaz pregleda i spremnost AR paketa.",
        "Posle generisanja možete pregledati model, pokrenuti regenerisanje ili poslati model na proveru kvaliteta.",
      ] as Array<string | ((...args: Array<string | number>) => string)>,
    },

    upload: {
      eyebrow: "Čarobnjak za vođeni upload fotografija",
      heading: "Otpremite 4 fotografije proizvoda",
      subtitle: "Provera fotografija se pokreće pre nego što proizvod uđe u 3D generisanje.",
      productImages: "Slike proizvoda",
      uploaded: "otpremljeno",
      formats: "JPG, PNG",
      readyToGenerate: "Spremno za generisanje",
      blocked: "Blokirano",
      startGeneration: "Pokreni generisanje",
      preflightHeading: "Rezultati provere pre leta",
    },

    statusLabels: {
      draft: "Nacrt",
      photos_uploaded: "Fotografije potrebne",
      generating: "Generisanje u toku",
      generation_failed: "Treba revizija",
      awaiting_review: "Čeka pregled",
      approved: "Odobreno",
      rejected: "Odbijeno",
      published: "Objavljeno",
      unpublished: "Nije objavljeno",
    },

    productCard: {
      viewProgress: "Pogledaj napredak",
      reviewModel: "Pregledaj model",
      publish: "Objavi",
      copyLiveLink: "Kopiraj aktivni link",
      open: "Otvori",
      regenerate: "Regeneriši",
      continue_: "Nastavi",
      delete: "Obriši",
      cancel: "Otkaži",
      deleteConfirm: "Obrisati ovaj model? Ova akcija je nepovratna.",
      deleting: "Brisanje...",
      arViews: "AR pregledi",
      storeClicks: "Klikovi na prodavnicu",
      photos: "foto",
    },

    productDetail: {
      eyebrow: "Detalji modela",
      backToProducts: "← Nazad na proizvode",
      previewSection: "Preview modela",
      noModel: "Model još nije generisan",
      noModelDesc: "Generisanje mora da se završi pre pregleda.",
      statusSection: "Status",
      infoSection: "Informacije",
      editSection: "Izmena detalja",
      editDesc: "Opciono — izmene se primenjuju na hostovanu stranicu.",
      productName: "Naziv proizvoda",
      category: "Kategorija",
      description: "Opis (opciono)",
      dimensionsHeading: "Dimenzije (cm)",
      widthLabel: "Š",
      heightLabel: "V",
      depthLabel: "D",
      storeUrl: "URL prodavnice",
      price: "Cena (opciono)",
      saveChanges: "Sačuvaj izmene",
      saving: "Čuvanje...",
      saved: "Sačuvano ✓",
      saveError: "Greška pri čuvanju. Pokušajte ponovo.",
      deleteModel: "Obriši model",
      deleteConfirm: "Obrisati ovaj model? Ova akcija je nepovratna i ne može se poništiti.",
      deleting: "Brisanje...",
      deleteError: "Greška pri brisanju. Pokušajte ponovo.",
      cancel: "Otkaži",
      photos: "fotografija",
      hostedLink: "Hostovani link",
      notPublished: "Nije objavljeno",
      pageViews: "Pregledi stranica",
      arClicks: "AR klikovi",
      storeClicks: "Klikovi na prodavnicu",
      viewerInteractions: "Interakcije",
      analytics: "Angažovanje",
      glbReady: "GLB ✓",
      usdzReady: "USDZ ✓",
      posterReady: "Poster ✓",
    },

    dashboardExtra: {
      overviewHeading: "Pregled",
      modelsLive: (n: number) => `${n} ${n === 1 ? "model aktivan" : "modela aktivnih"}`,
      arViewsWeek: (n: number) => `· ${n} AR ${n === 1 ? "pregled" : "pregleda"} ove nedelje`,
      startPublishing: "· počnite objavljivanje da vidite angažovanje",
      allProductsTable: "Svi proizvodi — tabelarni prikaz",
      pagesUsed: "objavljenih stranica korišćeno",
      planOf: "od 25",
      configWarning: "Podešavanje radnog prostora zahteva pažnju pre nego što se pravi podaci mogu sačuvati.",
      configNotConnected: "Produkcioni storage nije povezan. Završite podešavanje pre dodavanja pilot klijenata.",
      needsRevision: (n: number) => `${n} ${n === 1 ? "proizvod treba" : "proizvoda treba"} reviziju`,
      needsRevisionDesc: "Ponovo otpremite sa jasnijim fotografijama ili kontaktirajte podršku.",
      awaitingReviewCount: (n: number) => `${n} ${n === 1 ? "čeka" : "čekaju"} vaš pregled`,
      awaitingReviewDesc: "Proverite sličnost, razmeru i AR spremnost.",
      readyToPublish: (n: number) => `${n} odobreno — spremo za objavljivanje`,
      readyToPublishDesc: "Kopirajte hostovani link za vašu prodavnicu.",
      generatingCount: (n: number) => `${n} ${n === 1 ? "generisanje u toku" : "generisanja u toku"}`,
      generatingDesc: "Kreiranje 3D modela u toku.",
      pagesLiveCount: (n: number) => `${n} ${n === 1 ? "stranica aktivna" : "stranica aktivno"}`,
      pagesLiveDesc: "Podelite hostovane linkove u prodavnici, oglasima ili emailovima.",
      noProductsActions: "Kreirajte prvi AR proizvod da biste testirali upload, 3D pregled i objavljivanje hostovanog linka.",
      reachPlanLimit: "Dostignut limit plana",
    },

    statusExtra: {
      noActiveGeneration: "Nema aktivnog generisanja",
      noActiveDesc: "Pokrenite generisanje proizvoda, pa će ova stranica prikazati napredak uživo.",
      createBtn: "Kreiraj AR stranicu",
      loadingHeading: "Učitavanje statusa",
      loadingDesc: "Priprema tajmlajn generisanja.",
      processing: "Aplikacija kreira 3D model i pakuje ga za web i AR preglednik.",
      stepPhotosTitle: "Fotografije otpremljene",
      stepPhotosDetail: (count: number | string) => `${count} fotografija primljeno i uskladišteno.`,
      stepModelTitle: "Kreiranje modela",
      stepModelReady: "3D model je generisan.",
      stepPackagingTitle: "Pakovanje AR fajlova",
      stepPackagingReady: "GLB, USDZ i poster fajlovi su uskladišteni za preglednik.",
      stepPackagingFailed: "Pakovanje zaustavljeno zbog neuspeha generisanja.",
      stepPackagingPending: "Model će biti kopiran u storage čim se generisanje završi.",
      stepReviewTitle: "Spreman za pregled",
      stepReviewReady: "Otvorite preview, pregledajte model, zatim pošaljite na pregled kvaliteta.",
      stepReviewFailed: "Pokrenite novo generisanje nakon rešavanja problema iznad.",
      stepReviewPending: "Preview se otključava nakon završetka pakovanja.",
      currentStatusHeading: "Trenutni status",
      refreshing: "Osvežavanje",
      genProgress: "Napredak generisanja",
      complete: "% završeno",
      openModel: "Otvori generisani model",
      startAnother: "Pokreni novo generisanje",
      statusReady: "Spreman za pregled",
      statusNeedsPhotos: "Potrebne nove fotografije",
      statusCreating: "Kreiranje modela",
      statusQueued: "U redu čekanja",
    },
  },

  en: {
    nav: {
      products: "Products",
      createAr: "Create AR Page",
      publishedLinks: "Published Links",
      analytics: "Analytics",
      billing: "Billing",
      logout: "Log out",
      footer: "Models are human-reviewed before publishing. Pilot: 10–25 products.",
      brand: "Pilot workspace",
      demoBadge: "Pilot workspace",
    },
    langToggle: "SR",

    dashboard: {
      eyebrow: "Pilot Command Center",
      heading: "Your AR dashboard",
      subtitle: "Start by adding your first product. Real products, hosted links, and AR metrics will appear here after you create them.",
      createBtn: "+ Create AR page",
      catalogStatus: "Catalog status",
      noProducts: "No products yet",
      publishedPages: "Published pages",
      hostedLive: "Nothing published yet",
      arClicks: "AR clicks",
      noActivity: "No activity yet",
      storeClicks: "Store clicks",
      backToStore: "No clicks yet",
      nextActions: "Next required actions",
      emptyActionDesc: "Create the first AR product to test upload, 3D preview, and hosted-link publishing.",
      addProduct: "Add product",
      actionItemTitle: "Create your first AR product",
      actionItemDesc: "Enter product details, dimensions, and photos, then inspect the 3D model when it is ready.",
      planUsage: "Current plan usage",
      pagesPublished: "pilot hosted pages published.",
      billingNote: "Model creation is billed per approved model. Hosted-page subscription covers all live pages.",
      humanReviewed: "Human-reviewed before publishing",
      viewBilling: "View billing details →",
      productsHeading: "Products",
      productsDesc: "No real products yet. This table will show statuses, links, and metrics after you add your first product.",
      publishedLinksBtn: "Published links",
      emptyProductsTitle: "No products yet",
      emptyProductsDesc: "Create your first AR product to start testing the dashboard.",
    },

    table: {
      product: "Product",
      status: "Status",
      nextAction: "Next action",
      hostedLink: "Hosted link",
      arClicks: "AR clicks",
      storeClicks: "Store clicks",
      photos: "photos",
      copyLink: "Copy hosted link",
      notLive: "Not live yet",
      addPhotos: "Add photos",
      waitingModel: "Waiting for model",
      reviewPreview: "Review preview",
      publishLink: "Publish link",
      viewAnalytics: "View analytics",
      reviewDetails: "Review details",
      emptyTitle: "No products yet",
      emptyDescription: "Create your first AR product to see statuses, links, and metrics here.",
    },

    analytics: {
      eyebrow: "Analytics",
      heading: "Shopper engagement",
      subtitle: "Page views, 3D viewer interactions, AR clicks, and store CTA clicks — by product.",
      viewBilling: "View billing",
      pageViews: "Page views",
      allProducts: "All products",
      embedViews: "Embed views",
      embedded: "Embedded on stores",
      viewerInteractions: "Viewer interactions",
      engagements3d: "3D engagements",
      arClicks: "AR clicks",
      viewInRoom: "View in room",
      storeCta: "Store CTA clicks",
      backToStore: "Back to store",
      breakdown: "Product breakdown",
      breakdownDesc: "Engagement metrics for each published product page.",
      colProduct: "Product",
      colPageViews: "Page views",
      colEmbedViews: "Embed views",
      colInteractions: "Interactions",
      colArClicks: "AR clicks",
      colStoreClicks: "Store clicks",
      colTopDevices: "Top devices",
      noData: "No data yet",
    },

    billing: {
      eyebrow: "Billing",
      heading: "Pilot plan and costs",
      subtitle: "Per-approved-model fee plus a monthly hosted-page subscription. Simple and predictable.",
      viewAnalytics: "View analytics",
      planUsageHeading: "Current plan usage",
      planUsageSub: "10–25 SKU pilot",
      active: "Active",
      pagesPublished: "pilot hosted pages published",
      pageLive: "page live",
      pagesLive: "pages live",
      pageRemaining: "page remaining",
      pagesRemaining: "pages remaining",
      humanReviewed: "Human-reviewed before publishing",
      subscriptionHeading: "Subscription plan",
      subscriptionDesc: "Upgrade at any time. Changes take effect immediately.",
      currentPlan: "Current plan",
      popular: "Popular",
      custom: "Custom",
      perMonth: "/mo",
      skus: "SKUs",
      storage: "Storage",
      views: "Views",
      upgradeTo: "Upgrade to",
      downgradeTo: "Downgrade to",
      talkToUs: "Talk to us",
      pricingHeading: "Pricing breakdown",
      pricingDesc: "Billed per approved model plus a monthly subscription for hosted pages. Revision or regeneration is only charged when a new version is requested after an approved model already exists.",
      includedHeading: "What's included in the pilot",
      includedItems: [
        ["Guided photo upload", "Step-by-step checklist for all required product angles."],
        ["Model generation", "Automated generation run for each submitted product."],
        ["Human quality review", "Manual approval gate before any page goes live."],
        ["Hosted product page", "Public link for your store, email, ad, or QR code."],
        ["3D viewer and AR launch", "Shoppers inspect the product in 3D and launch AR on supported devices."],
        ["Engagement analytics", "Page views, AR clicks, and store CTA clicks — per product."],
      ] as [string, string][],
    },

    create: {
      eyebrow: "Create AR Page",
      heading: "Guided product setup",
      subtitle: "Add the product, upload the required photos, then start automatic 3D model generation.",
      backBtn: "Back to products",
      steps: ["Product details", "Dimensions", "Store URL", "Guided photo upload", "Generate 3D model"],
      detailsHeading: "Product details",
      productName: "Product name",
      category: "Product category",
      description: "Short product description",
      dimensionsHeading: "Dimensions",
      width: "Width cm",
      height: "Height cm",
      depth: "Depth cm",
      storeUrlHeading: "Store URL",
      storeUrl: "Product page on your store",
      price: "Display price optional",
      submitBtn: "Generate 3D model",
      photoEyebrow: "Guided photo upload",
      photoHeading: "Photos needed before generation",
      photoDesc: "Use clear, well-lit photos against a simple background. After generation, you will see the 3D preview before publishing.",
      photoChecklist: [
        ["Front", "Straight-on product photo"],
        ["Back", "Rear view with the full outline visible"],
        ["Left side", "Side profile for depth and legs or arms"],
        ["Right side", "Opposite side profile"],
        ["Top or angled view", "Shows depth, seat, surface, or shade shape"],
        ["Material/detail shots", "Close-ups of fabric, wood grain, hardware, or texture"],
        ["Scale/context shot", "Optional room or hand-scale photo when useful"],
      ] as [string, string][],
      ready: "Ready",
      needed: "Needed",
      uploadBtn: "Upload",
      changeBtn: "Change",
      submittingBtn: "Starting generation...",
      assumptionNote: (name: string) =>
        `${name} has enough core angles to start, but material/detail and scale photos improve the reviewer confidence score.`,
    },

    publishedLinks: {
      eyebrow: "Published Links",
      heading: "Live hosted product pages",
      subtitle: "Copy links for your store, ads, emails, or QR codes.",
      createBtn: "Create AR page",
      verifiedLive: "Verified and live",
      notPublished: "Not published",
      hostedLink: "Hosted link",
      preview: "Preview",
      availableAfter: "Available after approval and publishing.",
      ctaDestination: "CTA destination:",
      embedHeading: "Embed on your store",
      embedHint: "Paste this code into your product page (Shopify, WooCommerce, Wix, or a custom site).",
      copyEmbed: "Copy embed code",
    },

    approval: {
      eyebrow: "Approval status",
      heading: "Manual review controls publishing",
      subtitle: "No public hosted page goes live until the product model is approved.",
      checks: [
        "Model resembles product.",
        "Orientation and scale are reasonable.",
        "Textures and geometry are acceptable.",
        "Public preview loads before publishing.",
      ],
      reviewerNote: "Reviewer note:",
      merchantStatus: "Merchant status",
      merchantDesc: "Merchants see a simple review status. Internal rejection reasons can be translated into clear regeneration steps.",
      awaitingReview: "Awaiting review",
      hostedSettings: "Hosted page settings",
    },

    status: {
      eyebrow: "Generation status",
      subtitle: "Photos are processing now. The model appears here after generation and AR asset packaging finish.",
      photoSetFallback: "the active photo set",
      fallbackHeading: "What happens next",
      fallbackDesc: "The app generates the 3D model first, then packages web and AR files. If the result is poor, regeneration can run without changing the public page.",
      generationRunning: "3D generation running",
      providerJob: "Internal job",
      tripoAvailable: "Backup generation available",
      fallbackLocked: "Fallback locked",
      viewLastModel: "Open generated model",
      stageDetails: [
        (photoCount: number, photoSetId: string) =>
          `${photoCount} photos stored in ${photoSetId}.`,
        (passed: number, total: number) =>
          `${passed}/${total} checks passed before provider submission.`,
        (_provider: string, status: string) =>
          `Processing status: ${status}.`,
        "Raw provider output is stored before GLB, USDZ, poster, thumbnail, and metadata packaging.",
        "The app checks model load, size, dimensions, textures, preview render, and AR package readiness.",
        "After generation, you can inspect the model, regenerate it, or send it to quality review.",
      ] as Array<string | ((...args: Array<string | number>) => string)>,
    },

    upload: {
      eyebrow: "Guided photo upload wizard",
      heading: "Upload 4 product photos",
      subtitle: "Preflight checks run before a product can enter 3D generation.",
      productImages: "Product images",
      uploaded: "uploaded",
      formats: "JPG, PNG",
      readyToGenerate: "Ready to generate",
      blocked: "Blocked",
      startGeneration: "Start generation",
      preflightHeading: "Preflight results",
    },

    statusLabels: {
      draft: "Draft",
      photos_uploaded: "Photos needed",
      generating: "Generating",
      generation_failed: "Needs revision",
      awaiting_review: "Awaiting review",
      approved: "Approved",
      rejected: "Rejected",
      published: "Published",
      unpublished: "Unpublished",
    },

    productCard: {
      viewProgress: "View progress",
      reviewModel: "Review model",
      publish: "Publish",
      copyLiveLink: "Copy live link",
      open: "Open",
      regenerate: "Regenerate",
      continue_: "Continue",
      delete: "Delete",
      cancel: "Cancel",
      deleteConfirm: "Delete this model? This action cannot be undone.",
      deleting: "Deleting...",
      arViews: "AR views",
      storeClicks: "Store clicks",
      photos: "photo",
    },

    productDetail: {
      eyebrow: "Model details",
      backToProducts: "← Back to products",
      previewSection: "Model preview",
      noModel: "Model not generated yet",
      noModelDesc: "Generation must complete before the preview is available.",
      statusSection: "Status",
      infoSection: "Details",
      editSection: "Edit details",
      editDesc: "Optional — changes apply to the hosted page.",
      productName: "Product name",
      category: "Category",
      description: "Description (optional)",
      dimensionsHeading: "Dimensions (cm)",
      widthLabel: "W",
      heightLabel: "H",
      depthLabel: "D",
      storeUrl: "Store URL",
      price: "Price (optional)",
      saveChanges: "Save changes",
      saving: "Saving...",
      saved: "Saved ✓",
      saveError: "Error saving. Please try again.",
      deleteModel: "Delete model",
      deleteConfirm: "Delete this model? This action is permanent and cannot be undone.",
      deleting: "Deleting...",
      deleteError: "Error deleting. Please try again.",
      cancel: "Cancel",
      photos: "photos",
      hostedLink: "Hosted link",
      notPublished: "Not published",
      pageViews: "Page views",
      arClicks: "AR clicks",
      storeClicks: "Store clicks",
      viewerInteractions: "Interactions",
      analytics: "Engagement",
      glbReady: "GLB ✓",
      usdzReady: "USDZ ✓",
      posterReady: "Poster ✓",
    },

    dashboardExtra: {
      overviewHeading: "Overview",
      modelsLive: (n: number) => `${n} model${n !== 1 ? "s" : ""} live`,
      arViewsWeek: (n: number) => `· ${n} AR view${n !== 1 ? "s" : ""} this week`,
      startPublishing: "· start publishing to see engagement",
      allProductsTable: "All products — table view",
      pagesUsed: "published pages used",
      planOf: "of 25",
      configWarning: "Workspace setup needs attention before live product data can be saved.",
      configNotConnected: "Live workspace storage is not connected yet. Finish production setup before inviting pilot merchants.",
      needsRevision: (n: number) => `${n} product${n !== 1 ? "s" : ""} need${n === 1 ? "s" : ""} revision`,
      needsRevisionDesc: "Re-upload with clearer photos or contact support.",
      awaitingReviewCount: (n: number) => `${n} awaiting your review`,
      awaitingReviewDesc: "Check resemblance, scale, and AR readiness.",
      readyToPublish: (n: number) => `${n} approved — ready to publish`,
      readyToPublishDesc: "Copy the hosted link for your store.",
      generatingCount: (n: number) => `${n} generating`,
      generatingDesc: "3D model creation in progress.",
      pagesLiveCount: (n: number) => `${n} page${n !== 1 ? "s" : ""} live`,
      pagesLiveDesc: "Share hosted links in your store, ads, or emails to drive AR engagement.",
      noProductsActions: "Create the first AR product to test upload, 3D preview, and hosted-link publishing.",
      reachPlanLimit: "Plan limit reached",
    },

    statusExtra: {
      noActiveGeneration: "No active generation",
      noActiveDesc: "Start a product generation first, then this page will show live progress.",
      createBtn: "Create AR product",
      loadingHeading: "Loading status",
      loadingDesc: "Preparing the generation timeline.",
      processing: "The app is creating the 3D model and packaging it for the web and AR viewer.",
      stepPhotosTitle: "Photos uploaded",
      stepPhotosDetail: (count: number | string) => `${count} product photos were received and stored.`,
      stepModelTitle: "Creating model",
      stepModelReady: "The 3D model was generated.",
      stepPackagingTitle: "Packaging AR files",
      stepPackagingReady: "GLB, USDZ, and poster files are stored for the viewer.",
      stepPackagingFailed: "Packaging stopped because this generation run failed.",
      stepPackagingPending: "The model will be copied into storage as soon as generation finishes.",
      stepReviewTitle: "Ready to review",
      stepReviewReady: "Open the preview, inspect the model, then send it to quality review.",
      stepReviewFailed: "Start another generation after fixing the issue above.",
      stepReviewPending: "Preview unlocks after packaging finishes.",
      currentStatusHeading: "Current status",
      refreshing: "Refreshing",
      genProgress: "Generation progress",
      complete: "% complete",
      openModel: "Open generated model",
      startAnother: "Start another generation",
      statusReady: "Ready to review",
      statusNeedsPhotos: "Needs new photos",
      statusCreating: "Creating model",
      statusQueued: "Queued",
    },
  },
} as const

type Translations = (typeof t)[Lang]

const LangContext = createContext<{
  lang: Lang
  tr: Translations
  toggle: () => void
}>({
  lang: "en",
  tr: t.en,
  toggle: () => {},
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("sr")
  const toggle = () => setLang((l) => (l === "sr" ? "en" : "sr"))
  return (
    <LangContext.Provider value={{ lang, tr: t[lang], toggle }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
