"use client"

import { createContext, useContext, useState } from "react"

export type Lang = "sr" | "en"

export const t = {
  sr: {
    nav: {
      products: "Proizvodi",
      createAr: "Kreiraj AR stranicu",
      publishedLinks: "Objavljeni linkovi",
      analytics: "Analitika",
      billing: "Naplata",
      logout: "Odjavi se",
      footer: "Modeli su pregledani od strane čoveka pre objavljivanja. Pilot: 10–25 proizvoda.",
      brand: "Pilot komandni centar",
      demoBadge: "Demo prikaz",
    },
    langToggle: "EN",

    dashboard: {
      eyebrow: "Pilot komandni centar",
      subtitle: "Otpremi fotografije, pregledaj verifikovane AR stranice, objavi hostovane linkove i meri angažovanost kupaca.",
      createBtn: "+ Kreiraj AR stranicu",
      catalogStatus: "Status kataloga",
      pilotSkus: "Pilot SKU-ovi",
      publishedPages: "Objavljene stranice",
      hostedLive: "Hostovano i aktivno",
      arClicks: "AR klikovi",
      pilotTotal: "Pilot ukupno",
      storeClicks: "Klikovi na prodavnicu",
      backToStore: "Nazad u prodavnicu",
      nextActions: "Sledeće potrebne radnje",
      needsAttentionOne: "proizvod zahteva pažnju.",
      needsAttentionMany: "proizvoda zahteva pažnju.",
      addProduct: "Dodaj proizvod",
      actionItem1Title: "Vale Wall Shelf",
      actionItem1Desc: "Dodaj jednu oštriju fotografiju materijala/detalja pre pregleda generisanja.",
      actionItem2Title: "Mira Table Lamp",
      actionItem2Desc: "Čekanje na generisanje modela i pregled kvaliteta.",
      planUsage: "Korišćenje trenutnog plana",
      pagesPublished: "pilot hostovanih stranica objavljeno.",
      billingNote: "Kreiranje modela se naplaćuje po odobrenom modelu. Pretplata za hostovanu stranicu pokriva sve aktivne stranice.",
      humanReviewed: "Pregledano od strane čoveka pre objavljivanja",
      viewBilling: "Pogledaj detalje naplate →",
      productsHeading: "Proizvodi",
      productsDesc: "Akcija, status objavljivanja i performanse po proizvodu.",
      publishedLinksBtn: "Objavljeni linkovi",
    },

    table: {
      product: "Proizvod",
      status: "Status",
      nextAction: "Sledeća akcija",
      hostedLink: "Hostovani link",
      arClicks: "AR klikovi",
      storeClicks: "Klikovi na prodavnicu",
      photos: "fotografija",
      copyLink: "Kopiraj hostovani link",
      notLive: "Još nije aktivno",
      addPhotos: "Dodaj fotografije",
      waitingModel: "Čekanje na model",
      reviewPreview: "Pregledaj pregled",
      publishLink: "Objavi link",
      viewAnalytics: "Pogledaj analitiku",
      reviewDetails: "Pregledaj detalje",
    },

    analytics: {
      eyebrow: "Analitika",
      heading: "Angažovanost kupaca",
      subtitle: "Pregledi stranica, interakcije sa 3D pregledačem, AR klikovi i CTA klikovi na prodavnicu — po proizvodu.",
      viewBilling: "Pogledaj naplatu",
      pageViews: "Pregledi stranica",
      allProducts: "Svi proizvodi",
      viewerInteractions: "Interakcije sa pregledačem",
      engagements3d: "3D angažovanost",
      arClicks: "AR klikovi",
      viewInRoom: "Pogledaj u prostoriji",
      storeCta: "CTA klikovi na prodavnicu",
      backToStore: "Nazad u prodavnicu",
      breakdown: "Pregled po proizvodu",
      breakdownDesc: "Metrike angažovanosti za svaku objavljenu stranicu proizvoda.",
      colProduct: "Proizvod",
      colPageViews: "Pregledi",
      colInteractions: "Interakcije",
      colArClicks: "AR klikovi",
      colStoreClicks: "Klikovi na prodavnicu",
      colTopDevices: "Vodeći uređaji",
      noData: "Nema podataka",
    },

    billing: {
      eyebrow: "Naplata",
      heading: "Pilot plan i troškovi",
      subtitle: "Naknada po odobrenom modelu plus mesečna pretplata za hostovanu stranicu. Jednostavno i predvidivo.",
      viewAnalytics: "Pogledaj analitiku",
      planUsageHeading: "Korišćenje trenutnog plana",
      planUsageSub: "10–25 SKU pilot",
      active: "Aktivan",
      pagesPublished: "pilot hostovanih stranica objavljeno",
      pageLive: "stranica aktivno",
      pagesLive: "stranica aktivno",
      pageRemaining: "stranica preostalo",
      pagesRemaining: "stranica preostalo",
      humanReviewed: "Pregledano od strane čoveka pre objavljivanja",
      subscriptionHeading: "Plan pretplate",
      subscriptionDesc: "Nadogradite u bilo kom trenutku. Promene stupaju na snagu odmah.",
      currentPlan: "Trenutni plan",
      popular: "Popularno",
      custom: "Po dogovoru",
      perMonth: "/mes",
      skus: "SKU-ovi",
      storage: "Skladište",
      views: "Pregledi",
      upgradeTo: "Nadogradite na",
      downgradeTo: "Smanjite na",
      talkToUs: "Kontaktirajte nas",
      pricingHeading: "Pregled cena",
      pricingDesc: "Naplaćuje se po odobrenom modelu plus mesečna pretplata za hostovane stranice. Revizija ili regeneracija se naplaćuje samo kada se zatraži nova verzija nakon što odobreni model već postoji.",
      includedHeading: "Šta je uključeno u pilot",
      includedItems: [
        ["Vođeni upload fotografija", "Korak-po-korak lista za sve potrebne uglove proizvoda."],
        ["Generisanje modela", "Automatsko pokretanje generisanja za svaki poslati proizvod."],
        ["Pregled kvaliteta od strane čoveka", "Ručna kapija odobrenja pre nego što stranica postane aktivna."],
        ["Hostovana stranica proizvoda", "Javni link za vašu prodavnicu, email, oglas ili QR kod."],
        ["3D pregledač i AR pokretanje", "Kupci pregledaju proizvod u 3D i pokreću AR na podržanim uređajima."],
        ["Analitika angažovanosti", "Pregledi stranica, AR klikovi i CTA klikovi na prodavnicu — po proizvodu."],
      ] as [string, string][],
    },

    create: {
      eyebrow: "Kreiraj AR stranicu",
      heading: "Vođeno podešavanje proizvoda",
      subtitle: "Dodajte proizvod, otpremite potrebne fotografije, zatim pošaljite na generisanje i ručni pregled kvaliteta.",
      backBtn: "Nazad na proizvode",
      steps: ["Detalji proizvoda", "Dimenzije", "URL prodavnice", "Vođeni upload fotografija", "Pošalji na pregled"],
      detailsHeading: "Detalji proizvoda",
      productName: "Naziv proizvoda",
      category: "Kategorija proizvoda",
      description: "Kratki opis proizvoda",
      dimensionsHeading: "Dimenzije",
      width: "Širina cm",
      height: "Visina cm",
      depth: "Dubina cm",
      storeUrlHeading: "URL prodavnice",
      storeUrl: "Stranica proizvoda na vašoj prodavnici",
      price: "Prikaz cene (opciono)",
      submitBtn: "Pošalji na generisanje i pregled",
      photoEyebrow: "Vođeni upload fotografija",
      photoHeading: "Fotografije potrebne pre generisanja",
      photoDesc: "Koristite jasne, dobro osvetljene fotografije na jednostavnoj pozadini. Vaša stranica neće biti objavljena dok model ne prođe pregled.",
      photoChecklist: [
        ["Prednja strana", "Fotografija proizvoda direktno sa prednje strane"],
        ["Zadnja strana", "Pogled sa zadnje strane sa vidljivim punim obrisom"],
        ["Leva strana", "Bočni profil za dubinu i noge ili naslone"],
        ["Desna strana", "Profil suprotne strane"],
        ["Gornji ili kosi ugao", "Prikazuje dubinu, sedište, površinu ili oblik senke"],
        ["Fotografije materijala/detalja", "Krupni planovi tkanine, drvenih vlakana, metalne opreme ili teksture"],
        ["Fotografija za merilo/kontekst", "Opcionalna fotografija u prostoriji ili rukom kada je korisno"],
      ] as [string, string][],
      ready: "Spremno",
      needed: "Potrebno",
      uploadBtn: "Otpremi",
      changeBtn: "Zameni",
      assumptionNote: (name: string) =>
        `${name} ima dovoljno osnovnih uglova za početak, ali fotografije materijala/detalja i merila poboljšavaju ocenu poverenja recenzenta.`,
    },

    publishedLinks: {
      eyebrow: "Objavljeni linkovi",
      heading: "Aktivne hostovane stranice proizvoda",
      subtitle: "Kopirajte linkove za vašu prodavnicu, oglase, emailove ili QR kodove.",
      createBtn: "Kreiraj AR stranicu",
      verifiedLive: "Verifikovano i aktivno",
      notPublished: "Nije objavljeno",
      hostedLink: "Hostovani link",
      preview: "Pregled",
      availableAfter: "Dostupno nakon odobrenja i objavljivanja.",
      ctaDestination: "CTA odredište:",
    },

    approval: {
      eyebrow: "Status odobrenja",
      heading: "Ručni pregled kontroliše objavljivanje",
      subtitle: "Nijedna javna hostovana stranica ne postaje aktivna dok model proizvoda ne bude odobren.",
      checks: [
        "Model liči na proizvod.",
        "Orijentacija i razmera su ispravni.",
        "Teksture i geometrija su prihvatljivi.",
        "Javni pregled se učitava pre objavljivanja.",
      ],
      reviewerNote: "Napomena recenzenta:",
      merchantStatus: "Status prodavca",
      merchantDesc: "Prodavci vide jednostavan status pregleda. Interna razloga za odbijanje mogu biti prevedena u jasne korake za regeneraciju.",
      awaitingReview: "Na čekanju pregleda",
      hostedSettings: "Podešavanja hostovane stranice",
    },

    status: {
      eyebrow: "Status generisanja",
      subtitle: "Meshy je primarni provajder. Tripo je rezervisan kao ručna rezervna opcija.",
      photoSetFallback: "aktivnom setu fotografija",
      fallbackHeading: "Kontrola rezervne opcije",
      fallbackDesc: "Administratori mogu ponoviti sa Tripo-om ako Meshy ne uspe ili vrati neupotrebljivu geometriju. Ovo namerno nije izloženo prodavcima.",
      generationRunning: "Generisanje u toku",
      providerJob: "Posao provajdera",
      tripoAvailable: "Tripo rezervna opcija dostupna",
      fallbackLocked: "Rezervna opcija zaključana",
      viewLastModel: "Pogledaj poslednji uspešan model",
      stageDetails: [
        (photoCount: number, photoSetId: string) =>
          `${photoCount} fotografija uskladišteno u ${photoSetId}.`,
        (passed: number, total: number) =>
          `${passed}/${total} provera prošlo pre slanja provajderu.`,
        (provider: string, status: string) =>
          `Provajder: ${provider}. Status: ${status}.`,
        "Sirovi izlaz provajdera se skladišti pre pakovanja GLB, USDZ, postera, sličice i metapodataka.",
        "Aplikacija proverava učitavanje modela, veličinu, dimenzije, teksture, prikaz pregleda i spremnost AR paketa.",
        "Recenzent odobrava, odbija ili zahteva regeneraciju.",
      ] as Array<string | ((...args: string[] | number[]) => string)>,
    },

    upload: {
      eyebrow: "Čarobnjak za vođeni upload fotografija",
      heading: "Otpremite 8–20 fotografija proizvoda",
      subtitle: "Faza 2 pokretanjem kontrola pre leta pre nego što proizvod može ući u Meshy generisanje.",
      productImages: "Slike proizvoda",
      uploaded: "otpremljeno",
      formats: "JPG, PNG, WebP",
      readyToGenerate: "Spremno za generisanje",
      blocked: "Blokirano",
      startGeneration: "Pokreni generisanje",
      preflightHeading: "Rezultati provere pre leta",
    },
  },

  en: {
    nav: {
      products: "Products",
      createAr: "Create AR Page",
      publishedLinks: "Published Links",
      analytics: "Analytics",
      billing: "Billing",
      logout: "Log out",
      footer: "Models are human-reviewed before publishing. Pilot: 10–25 products.",
      brand: "Pilot Command Center",
      demoBadge: "Demo view",
    },
    langToggle: "SR",

    dashboard: {
      eyebrow: "Pilot Command Center",
      subtitle: "Upload photos, review verified AR pages, publish hosted links, and measure shopper engagement.",
      createBtn: "+ Create AR page",
      catalogStatus: "Catalog status",
      pilotSkus: "Pilot SKUs",
      publishedPages: "Published pages",
      hostedLive: "Hosted and live",
      arClicks: "AR clicks",
      pilotTotal: "Pilot total",
      storeClicks: "Store clicks",
      backToStore: "Back to store",
      nextActions: "Next required actions",
      needsAttentionOne: "product needs attention.",
      needsAttentionMany: "products need attention.",
      addProduct: "Add product",
      actionItem1Title: "Vale Wall Shelf",
      actionItem1Desc: "Add one sharper material/detail photo before generation review.",
      actionItem2Title: "Mira Table Lamp",
      actionItem2Desc: "Waiting for model generation and quality review.",
      planUsage: "Current plan usage",
      pagesPublished: "pilot hosted pages published.",
      billingNote: "Model creation is billed per approved model. Hosted-page subscription covers all live pages.",
      humanReviewed: "Human-reviewed before publishing",
      viewBilling: "View billing details →",
      productsHeading: "Products",
      productsDesc: "Action, publishing state, and product-level performance.",
      publishedLinksBtn: "Published links",
    },

    table: {
      product: "Product",
      status: "Status",
      nextAction: "Next action",
      hostedLink: "Hosted link",
      arClicks: "AR clicks",
      storeClicks: "Store clicks",
      photos: "photos",
      copyLink: "Copy hosted link",
      notLive: "Not live yet",
      addPhotos: "Add photos",
      waitingModel: "Waiting for model",
      reviewPreview: "Review preview",
      publishLink: "Publish link",
      viewAnalytics: "View analytics",
      reviewDetails: "Review details",
    },

    analytics: {
      eyebrow: "Analytics",
      heading: "Shopper engagement",
      subtitle: "Page views, 3D viewer interactions, AR clicks, and store CTA clicks — by product.",
      viewBilling: "View billing",
      pageViews: "Page views",
      allProducts: "All products",
      viewerInteractions: "Viewer interactions",
      engagements3d: "3D engagements",
      arClicks: "AR clicks",
      viewInRoom: "View in room",
      storeCta: "Store CTA clicks",
      backToStore: "Back to store",
      breakdown: "Product breakdown",
      breakdownDesc: "Engagement metrics for each published product page.",
      colProduct: "Product",
      colPageViews: "Page views",
      colInteractions: "Interactions",
      colArClicks: "AR clicks",
      colStoreClicks: "Store clicks",
      colTopDevices: "Top devices",
      noData: "No data yet",
    },

    billing: {
      eyebrow: "Billing",
      heading: "Pilot plan and costs",
      subtitle: "Per-approved-model fee plus a monthly hosted-page subscription. Simple and predictable.",
      viewAnalytics: "View analytics",
      planUsageHeading: "Current plan usage",
      planUsageSub: "10–25 SKU pilot",
      active: "Active",
      pagesPublished: "pilot hosted pages published",
      pageLive: "page live",
      pagesLive: "pages live",
      pageRemaining: "page remaining",
      pagesRemaining: "pages remaining",
      humanReviewed: "Human-reviewed before publishing",
      subscriptionHeading: "Subscription plan",
      subscriptionDesc: "Upgrade at any time. Changes take effect immediately.",
      currentPlan: "Current plan",
      popular: "Popular",
      custom: "Custom",
      perMonth: "/mo",
      skus: "SKUs",
      storage: "Storage",
      views: "Views",
      upgradeTo: "Upgrade to",
      downgradeTo: "Downgrade to",
      talkToUs: "Talk to us",
      pricingHeading: "Pricing breakdown",
      pricingDesc: "Billed per approved model plus a monthly subscription for hosted pages. Revision or regeneration is only charged when a new version is requested after an approved model already exists.",
      includedHeading: "What's included in the pilot",
      includedItems: [
        ["Guided photo upload", "Step-by-step checklist for all required product angles."],
        ["Model generation", "Automated generation run for each submitted product."],
        ["Human quality review", "Manual approval gate before any page goes live."],
        ["Hosted product page", "Public link for your store, email, ad, or QR code."],
        ["3D viewer and AR launch", "Shoppers inspect the product in 3D and launch AR on supported devices."],
        ["Engagement analytics", "Page views, AR clicks, and store CTA clicks — per product."],
      ] as [string, string][],
    },

    create: {
      eyebrow: "Create AR Page",
      heading: "Guided product setup",
      subtitle: "Add the product, upload the required photos, then submit it for generation and human quality review.",
      backBtn: "Back to products",
      steps: ["Product details", "Dimensions", "Store URL", "Guided photo upload", "Submit for review"],
      detailsHeading: "Product details",
      productName: "Product name",
      category: "Product category",
      description: "Short product description",
      dimensionsHeading: "Dimensions",
      width: "Width cm",
      height: "Height cm",
      depth: "Depth cm",
      storeUrlHeading: "Store URL",
      storeUrl: "Product page on your store",
      price: "Display price optional",
      submitBtn: "Submit for generation and review",
      photoEyebrow: "Guided photo upload",
      photoHeading: "Photos needed before generation",
      photoDesc: "Use clear, well-lit photos against a simple background. Your page will not publish until the model passes review.",
      photoChecklist: [
        ["Front", "Straight-on product photo"],
        ["Back", "Rear view with the full outline visible"],
        ["Left side", "Side profile for depth and legs or arms"],
        ["Right side", "Opposite side profile"],
        ["Top or angled view", "Shows depth, seat, surface, or shade shape"],
        ["Material/detail shots", "Close-ups of fabric, wood grain, hardware, or texture"],
        ["Scale/context shot", "Optional room or hand-scale photo when useful"],
      ] as [string, string][],
      ready: "Ready",
      needed: "Needed",
      uploadBtn: "Upload",
      changeBtn: "Change",
      assumptionNote: (name: string) =>
        `${name} has enough core angles to start, but material/detail and scale photos improve the reviewer confidence score.`,
    },

    publishedLinks: {
      eyebrow: "Published Links",
      heading: "Live hosted product pages",
      subtitle: "Copy links for your store, ads, emails, or QR codes.",
      createBtn: "Create AR page",
      verifiedLive: "Verified and live",
      notPublished: "Not published",
      hostedLink: "Hosted link",
      preview: "Preview",
      availableAfter: "Available after approval and publishing.",
      ctaDestination: "CTA destination:",
    },

    approval: {
      eyebrow: "Approval status",
      heading: "Manual review controls publishing",
      subtitle: "No public hosted page goes live until the product model is approved.",
      checks: [
        "Model resembles product.",
        "Orientation and scale are reasonable.",
        "Textures and geometry are acceptable.",
        "Public preview loads before publishing.",
      ],
      reviewerNote: "Reviewer note:",
      merchantStatus: "Merchant status",
      merchantDesc: "Merchants see a simple review status. Internal rejection reasons can be translated into clear regeneration steps.",
      awaitingReview: "Awaiting review",
      hostedSettings: "Hosted page settings",
    },

    status: {
      eyebrow: "Generation status",
      subtitle: "Meshy is the primary provider. Tripo is reserved as a manual fallback.",
      photoSetFallback: "the active photo set",
      fallbackHeading: "Fallback control",
      fallbackDesc: "Admins can retry with Tripo if Meshy fails or returns unusable geometry. This is intentionally not exposed to merchants.",
      generationRunning: "Generation running",
      providerJob: "Provider job",
      tripoAvailable: "Tripo fallback available",
      fallbackLocked: "Fallback locked",
      viewLastModel: "View last successful model",
      stageDetails: [
        (photoCount: number, photoSetId: string) =>
          `${photoCount} photos stored in ${photoSetId}.`,
        (passed: number, total: number) =>
          `${passed}/${total} checks passed before provider submission.`,
        (provider: string, status: string) =>
          `Provider: ${provider}. Status: ${status}.`,
        "Raw provider output is stored before GLB, USDZ, poster, thumbnail, and metadata packaging.",
        "The app checks model load, size, dimensions, textures, preview render, and AR package readiness.",
        "A reviewer approves, rejects, or requests regeneration.",
      ] as Array<string | ((...args: string[] | number[]) => string)>,
    },

    upload: {
      eyebrow: "Guided photo upload wizard",
      heading: "Upload 8-20 product photos",
      subtitle: "Phase 2 runs preflight checks before a product can enter Meshy generation.",
      productImages: "Product images",
      uploaded: "uploaded",
      formats: "JPG, PNG, WebP",
      readyToGenerate: "Ready to generate",
      blocked: "Blocked",
      startGeneration: "Start generation",
      preflightHeading: "Preflight results",
    },
  },
} as const

type Translations = typeof t.sr

const LangContext = createContext<{
  lang: Lang
  tr: Translations
  toggle: () => void
}>({
  lang: "sr",
  tr: t.sr,
  toggle: () => {},
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("sr")
  const toggle = () => setLang((l) => (l === "sr" ? "en" : "sr"))
  return (
    <LangContext.Provider value={{ lang, tr: t[lang], toggle }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
